server:
  port: 8877
  servlet:
    context-path: /svc-ai-utilities
spring:
  application:
    name: AiUtilities
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

gemini:
  api:
    key: AIzaSyDOMHApBSL5sVWqZycm8zZg2c8HP8bpx1M
